steps:
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'version']
  - name: 'mirror.gcr.io/library/golang'
    args: ['go', 'test']
    dir: 'function/dir/from/repo/root'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'faascicd', '[YOUR_FUNCTION_TRIGGER]', '--runtime', 'go113', '--entry-point', '[YOUR_FUNCTION_NAME_IN_CODE]']
    dir: 'function/dir/from/repo/root
